### ISSUE TITLE
Testing my wonderful machine

### ISSUE THREAD

**Issue by NaiveMachine** [NaiveMachine/TestMachine#1]
Test bounty

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Contract address: [0x8f67e82ba5ee8df19540540a8b557b4de7c0aabc](https://ropsten.etherscan.io/address/0x8f67e82ba5ee8df19540540a8b557b4de7c0aabc)
![QR Code](https://openbounty.status.im:444/qr/NaiveMachine/TestMachine/bounty/1/5d0087f16290187ce3a4be75bfeba6d4719c72cf364955ebe45f6b69fb189f99/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
